import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  topContainer: {
    width: "90%",
    height: 90,
    backgroundColor: "#003153",
    marginTop: 8,
    marginLeft: 8,
    marginRight: 8,
    alignItems: "center",
    alignSelf: "center",
    justifyContent: "center",
    borderRadius: 40,
    zIndex: 2,
    shadowOffset: { width: 0, height: 8 },
    shadowColor: "#171717",
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 8,
    gap: 5,
  },
  infoContainer: {
    width: "70%",
    height: 30,
    backgroundColor: "#fff",
    alignItems: "center",
    alignSelf: "center",
    justifyContent: "center",
    borderBottomLeftRadius: 18,
    borderBottomRightRadius: 18,
    shadowOffset: { width: 0, height: 2 },
    shadowColor: "#171717",
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 2,
    zIndex: 1,
    flexDirection: "row",
  },
  topFlatList: {
    width: "90%",
    flexDirection: "row",
    alignSelf: "center",
    justifyContent: "center",
    marginLeft: 10,
    marginRight: 10,
  },
  text: {
    paddingRight: 15,
    paddingLeft: 15,
    fontSize: 14,
    color: "#def2fa",
    width: "100%",
    textAlign: "center",
  },
  foundText: {
    bottom: 10,
    paddingRight: 15,
    paddingLeft: 15,
    fontSize: 14,
    color: "#def2fa",
    width: "100%",
    textAlign: "center",
  },
  infoText: {
    paddingBottom:5,
    fontSize: 14,
    color: "#016894",
    width: "100%",
    textAlign: "center",
  },
  images: {
    width: 50,
    height: 50,
    marginLeft: -10,
    marginRight: -10,
    borderRadius: 50,
    justifyContent: "center",
    alignItems: "center",
  },
  lastImage: {
    width: 50,
    height: 50,
    borderRadius: 50,
    justifyContent: "center",
    position: "absolute",
  },
  restText: {
    fontWeight: "bold",
    fontSize: 16,
    color: "white",
    width: "100%",
    textAlign: "center",
  },
});

export default styles;
