/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_appsync_graphqlEndpoint": "https://6dg6cbf3lvgnvakjb2apzh7rde.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-uwhkdh6wejbihlniulmjillf5y",
    "aws_cognito_identity_pool_id": "eu-west-1:2a7b5a7f-fde7-4629-928c-7a42f3902f18",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_1tpYOOLEH",
    "aws_user_pools_web_client_id": "2m1rnmvcv7gb99c530s5peichb",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "NAME",
        "PHONE_NUMBER"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "rivetspacef36c220ed25f4408baf82c64fe9e1505225735-staging",
    "aws_user_files_s3_bucket_region": "eu-west-1"
};


export default awsmobile;
